# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161015_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Phone',
            new_name='phone',
        ),
    ]
