# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_id',
            old_name='email_id',
            new_name='user_name',
        ),
    ]
