# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_id_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rec_email',
            field=models.CharField(default=123123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_id',
            name='email_id',
            field=models.CharField(max_length=100),
        ),
    ]
