# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='intern',
            field=models.CharField(default='', max_length=100),
        ),
    ]
