# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161015_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_id',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='user_id',
            name='password',
        ),
        migrations.AddField(
            model_name='user_id',
            name='internaldate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
